name: Build and deploy website

on:
  push:
    branches:
      - astro

jobs:
  build-deploy:
    name: 🚀 Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Get latest code
        uses: actions/checkout@v4

      - name: 🫓 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📥 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🔨 Build website
        run: bunx --bun astro build

      - name: 🚚 Deploy website
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: bun run deploy
