name: Build and deploy website

on:
  push:
    branches:
      - astro

jobs:
  build-deploy:
    name: 🚀 Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🫓 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📥 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🔨 Build website
        run: bunx --bun astro build

      - name: 📦 Deploy website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /domains/sylviadieta.pl/public_html/
          protocol: ftps
          timeout: 20000
          # dangerous-clean-slate: true
          dry-run: true
          log-level: verbose
